# Generated by Django 4.0 on 2021-12-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211231_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
