# Generated by Django 3.2.8 on 2022-02-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_urlmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='original_url',
            field=models.URLField(max_length=500),
        ),
    ]
