# Generated by Django 4.0.4 on 2023-02-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_urlmodel_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='page_info',
            field=models.CharField(default="You'll find out more when you open the link", max_length=500),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='redirect',
            field=models.BooleanField(default=False),
        ),
    ]
