# Generated by Django 4.0.4 on 2023-02-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_urlmodel_page_info_alter_urlmodel_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='page_info',
            field=models.CharField(blank=True, default="You'll find out more when you open the link", max_length=500, null=True),
        ),
    ]
