# Generated by Django 4.0.4 on 2023-02-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_urlmodel_metadescription_urlmodel_metaimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='page_info',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
