# Generated by Django 4.0.4 on 2023-09-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_urlmodel_page_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='page_info',
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='metadescription',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
