# Generated by Django 4.0.4 on 2023-09-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_urlmodel_page_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='custom_meta',
            field=models.BooleanField(default=False),
        ),
    ]
